# This is a basic workflow to help you get started with Actions

name: deployerman

# Controls when the workflow will run
on:
  push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job to build and deploy
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - run: git status
      - uses: actions/setup-node@v3 #this will install Node and npm on Ubuntu
        with:
          node-version: '14.x'
      - run: npm install -g @angular/cli > /dev/null
      - run: npm install
        working-directory: ./frontend
      - run: ng build --output-path=../backend/dist --base-href /static/
        working-directory: ./frontend
      - run: git add -f backend/dist
      # Deploy to another repo
      - name: Deploy to full app to heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "backend" # <- This will point to the api folder in your project

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Done ig???